### PR TITLE
fix: remove incorrect peer dependency warning

### PR DESCRIPTION
**Pull request by PascalPflaum**

### CODE REVIEW

**Comment by zoetrope69** [comment]
Hi @patrickhulce what do you think to this change?

**Comment by patrickhulce** [comment]
Oh oops sorry about missing this @PascalPflaum! :)

@zaccolley have you tested it and it's working with 2.x of umzug?

**Comment by zoetrope69** [comment]
We're using:

```
   "umzug": "^2.1.0",
    "umzug-mongo": "^1.2.0"
```

And it's working fine

**Review by patrickhulce — APPROVED** [review]

**Comment by patrickhulce** [comment]
thanks again for the fix and ping @PascalPflaum and @zaccolley!

**Pull request merged**
